### ISSUE TITLE
Is this the official repro for MoPaD?

### ISSUE THREAD

**Issue by barsch** [geophysics/MoPaD#1]
Shouldn't MoPaD not be part of @emolch's repros? Don't know if Lars has a GitHub account. No offence meant - just curiosity ;)

Main reason is that there are a few patches to MoPaD within ObsPy which should be incorporated into the "official" repository.

Also personally I would like to refactor this file a bit (removing unsed vars / introduce PEP8). A bit problematic is that there are no tests written to ensure that refactoring does not break functionality :/

Cheers,
Robert

**Comment by emolch** [comment]
> Also personally I would like to refactor this file a bit (removing  
> unsed vars / introduce PEP8). A bit problematic is that there are no  
> tests written to ensure that refactoring does not break  
> functionality :/

I already did quite a lot of restructuring on that code about an year  
ago. My original intention was to split mopad into separate  
submodules: one for the moment tensor decomposition and such, one for  
plotting, and one for the command line interface. Then I found print  
statements in getter methods and other weird constructs which urged me  
to rewrite large portions of the code, so I lost focus as I did not  
make quick progress and had some more important stuff to work on.  
However Lars (@geophysics) should have my changes somewhere in his  
original SVN repository as a branch. Maybe he can put that stuff to a  
branch in the git repos, so that I can continue when I am back from my  
Elternzeit...

Cheers!
Sebastian

**Comment by barsch** [comment]
@emolch: jupp there are some really strange artefacts in this code ;)

+1 for splitting this huge code into submodules - loading this file takes ages!

anyway closing this ticket for now as this is the official repro for mopad - good to know!
